version: "3.8"

services:
  laravel:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
    container_name: laravel_ecommerce_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www
    depends_on:
      - mariadb
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  mariadb:
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
    container_name: ecommerce_mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}

volumes:
  db_data:
