FROM mariadb:10.5

# Set environment variables (optional; these can also be set in docker-compose)
ENV MYSQL_DATABASE=laravel
ENV MYSQL_USER=laravel
ENV MYSQL_PASSWORD=secret
ENV MYSQL_ROOT_PASSWORD=root

# Expose the default MariaDB port
EXPOSE 3306