FROM mariadb:10.5

ENV MYSQL_DATABASE=laravel_ecommerce_app_db
ENV MYSQL_USER=laravel_ecommerce_app_db_username
ENV MYSQL_PASSWORD=gregs32afsdgsaAsfdsBEWawdP0w3qasf
ENV MYSQL_ROOT_PASSWORD=root

EXPOSE 3306